'use client';

import { useMemo, useState } from 'react';
import type { ColumnDef } from '@tanstack/react-table';
import { BarChart3, Download, FileSpreadsheet, Filter, LineChart, PieChart, TrendingDown, TrendingUp, UsersRound } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart as RechartsLineChart, Pie, PieChart as RechartsPieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Breadcrumbs } from '@/components/dashboard/breadcrumbs';
import { SimpleDataTable } from '@/components/dashboard/simple-data-table';
import { StatCard } from '@/components/dashboard/stat-card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Select } from '@/components/ui/select';
import {
  agentPerformance,
  developerPerformance,
  discoverySourcePerformance,
  exportHistory,
  formatReportMoney,
  leadFunnel,
  monthlyPerformance,
  propertyMix,
  reportInsights,
  type AnalyticsScope,
  type ExportRecord,
  type ReportInsightRecord,
  type ReportStatus,
} from '@/lib/reports-data';

const insightTone: Record<ReportStatus, 'success' | 'warning' | 'danger' | 'muted'> = {
  healthy: 'success',
  warning: 'warning',
  danger: 'danger',
  neutral: 'muted',
};

const insightLabel: Record<ReportStatus, string> = {
  healthy: 'Healthy',
  warning: 'Needs attention',
  danger: 'Critical',
  neutral: 'Neutral',
};

const chartPalette = ['#059669', '#b98d24', '#0f172a', '#64748b', '#dc2626'];

export function ReportsAnalyticsWorkspace({ scope = 'agency' }: { scope?: AnalyticsScope }) {
  const [period, setPeriod] = useState('last_6_months');
  const [activeReport, setActiveReport] = useState<'overview' | 'funnel' | 'agents' | 'developer' | 'exports'>('overview');

  const totals = useMemo(() => {
    const inquiries = monthlyPerformance.reduce((sum, item) => sum + item.inquiries, 0);
    const viewings = monthlyPerformance.reduce((sum, item) => sum + item.viewings, 0);
    const deals = monthlyPerformance.reduce((sum, item) => sum + item.deals, 0);
    const revenue = monthlyPerformance.reduce((sum, item) => sum + item.revenue, 0);
    const expenses = monthlyPerformance.reduce((sum, item) => sum + item.expenses, 0);
    const conversion = Math.round((deals / inquiries) * 100);
    return { inquiries, viewings, deals, revenue, expenses, net: revenue - expenses, conversion };
  }, []);

  const scopedInsights = useMemo(() => {
    if (scope === 'developer') return reportInsights.filter((insight) => insight.owner === 'Developer' || insight.owner === 'Agency Admin');
    if (scope === 'finance') return reportInsights.filter((insight) => insight.owner === 'Finance Staff' || insight.owner === 'Agency Admin');
    if (scope === 'super-admin') return reportInsights;
    return reportInsights.filter((insight) => insight.owner !== 'Developer');
  }, [scope]);

  const insightColumns: ColumnDef<ReportInsightRecord>[] = [
    { header: 'Insight', cell: ({ row }) => <div><p className="font-bold text-slate-950">{row.original.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{row.original.message}</p></div> },
    { header: 'Owner', accessorKey: 'owner' },
    { header: 'Status', cell: ({ row }) => <Badge variant={insightTone[row.original.status]}>{insightLabel[row.original.status]}</Badge> },
  ];

  const exportColumns: ColumnDef<ExportRecord>[] = [
    { header: 'Report', accessorKey: 'reportName' },
    { header: 'Scope', cell: ({ row }) => <Badge variant="muted">{row.original.scope}</Badge> },
    { header: 'Format', accessorKey: 'format' },
    { header: 'Generated by', accessorKey: 'generatedBy' },
    { header: 'Generated at', accessorKey: 'generatedAt' },
    { header: 'Status', cell: ({ row }) => <Badge variant={row.original.status === 'ready' ? 'success' : row.original.status === 'queued' ? 'warning' : 'danger'}>{row.original.status}</Badge> },
  ];

  const title = scope === 'super-admin' ? 'Platform Reports & Activity' : scope === 'developer' ? 'Developer Reports & Analytics' : scope === 'finance' ? 'Finance Reports & Analytics' : 'Agency Reports & Analytics';
  const description = scope === 'developer'
    ? 'Track units, project progress, sales velocity and delivery risk across development projects.'
    : scope === 'finance'
      ? 'Watch revenue, expenses, payroll pressure and reporting exports from one finance control desk.'
      : scope === 'super-admin'
        ? 'Monitor platform-wide activity, lead performance, agency health and growth signals.'
        : 'Turn property, CRM, follow-up, referral and finance activity into clear decisions.';

  return (
    <div className="space-y-6">
      <Breadcrumbs />
      <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
        <div>
          <h1 className="text-3xl font-black text-slate-950">{title}</h1>
          <p className="mt-2 max-w-3xl text-slate-500">{description}</p>
        </div>
        <div className="flex flex-wrap gap-3">
          <Select value={period} onChange={(event) => setPeriod(event.target.value)} className="w-[180px]">
            <option value="last_30_days">Last 30 days</option>
            <option value="last_90_days">Last 90 days</option>
            <option value="last_6_months">Last 6 months</option>
            <option value="year_to_date">Year to date</option>
          </Select>
          <Button variant="secondary"><Filter className="h-4 w-4" /> Filter</Button>
          <Button variant="gold"><Download className="h-4 w-4" /> Export</Button>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Total inquiries" value={totals.inquiries.toString()} change={`${totals.viewings} viewings booked`} icon={UsersRound} />
        <StatCard label="Closed deals" value={totals.deals.toString()} change={`${totals.conversion}% lead-to-deal conversion`} icon={TrendingUp} />
        <StatCard label="Revenue" value={formatReportMoney(totals.revenue)} change="Recorded across selected period" icon={LineChart} />
        <StatCard label="Net balance" value={formatReportMoney(totals.net)} change={`${formatReportMoney(totals.expenses)} expenses`} icon={totals.net > 0 ? TrendingUp : TrendingDown} />
      </div>

      <div className="flex flex-wrap gap-2">
        {[
          ['overview', 'Overview'],
          ['funnel', 'Lead funnel'],
          ['agents', 'Agent performance'],
          ['developer', 'Developer analytics'],
          ['exports', 'Exports'],
        ].map(([value, label]) => <Button key={value} variant={activeReport === value ? 'default' : 'outline'} size="sm" onClick={() => setActiveReport(value as typeof activeReport)}>{label}</Button>)}
      </div>

      {(activeReport === 'overview' || activeReport === 'funnel') && (
        <div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
          <Card>
            <CardHeader><CardTitle>Revenue and activity trend</CardTitle><CardDescription>Revenue must be compared against actual viewings and deals. Vanity traffic is not performance.</CardDescription></CardHeader>
            <CardContent className="h-[320px]">
              <ResponsiveContainer width="100%" height="100%">
                <RechartsLineChart data={monthlyPerformance} margin={{ left: 0, right: 12, top: 10, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="month" />
                  <YAxis />
                  <Tooltip formatter={(value, name) => name === 'revenue' || name === 'expenses' ? formatReportMoney(Number(value)) : value} />
                  <Line type="monotone" dataKey="revenue" stroke="#059669" strokeWidth={3} dot={false} />
                  <Line type="monotone" dataKey="expenses" stroke="#b98d24" strokeWidth={3} dot={false} />
                  <Line type="monotone" dataKey="deals" stroke="#0f172a" strokeWidth={2} dot={false} />
                </RechartsLineChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>

          <Card>
            <CardHeader><CardTitle>Property mix</CardTitle><CardDescription>Current listing distribution by category.</CardDescription></CardHeader>
            <CardContent className="h-[320px]">
              <ResponsiveContainer width="100%" height="100%">
                <RechartsPieChart>
                  <Pie data={propertyMix} dataKey="value" nameKey="name" innerRadius={55} outerRadius={95} paddingAngle={4}>
                    {propertyMix.map((entry, index) => <Cell key={entry.name} fill={chartPalette[index % chartPalette.length]} />)}
                  </Pie>
                  <Tooltip />
                </RechartsPieChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
        </div>
      )}

      {(activeReport === 'overview' || activeReport === 'funnel') && (
        <div className="grid gap-6 xl:grid-cols-2">
          <Card>
            <CardHeader><CardTitle>Lead conversion funnel</CardTitle><CardDescription>This is where weak agencies expose themselves. Leads mean nothing if they do not move.</CardDescription></CardHeader>
            <CardContent className="space-y-4">
              {leadFunnel.map((stage) => <div key={stage.stage}><div className="mb-2 flex items-center justify-between text-sm"><span className="font-bold text-slate-800">{stage.stage}</span><span className="text-slate-500">{stage.count} • {stage.conversion}%</span></div><div className="h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full bg-emerald-500" style={{ width: `${stage.conversion}%` }} /></div></div>)}
            </CardContent>
          </Card>

          <Card>
            <CardHeader><CardTitle>Discovery source performance</CardTitle><CardDescription>Compare where leads come from against what actually converts.</CardDescription></CardHeader>
            <CardContent className="h-[300px]">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={discoverySourcePerformance}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="source" />
                  <YAxis />
                  <Tooltip />
                  <Bar dataKey="leads" fill="#64748b" radius={[8, 8, 0, 0]} />
                  <Bar dataKey="converted" fill="#059669" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
        </div>
      )}

      {(activeReport === 'overview' || activeReport === 'agents') && (
        <Card>
          <CardHeader><CardTitle>Agent performance</CardTitle><CardDescription>Reward conversion and revenue, not noise. Busy agents are not automatically productive agents.</CardDescription></CardHeader>
          <CardContent className="space-y-4">
            {agentPerformance.map((agent) => <div key={agent.agent} className="rounded-2xl border border-slate-100 p-4"><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><p className="font-bold text-slate-950">{agent.agent}</p><p className="text-xs text-slate-500">{agent.leads} leads • {agent.viewings} viewings • {agent.deals} deals</p></div><Badge variant={agent.conversionRate >= 10 ? 'success' : 'warning'}>{agent.conversionRate}% conversion</Badge></div><div className="mt-3 flex items-center justify-between text-sm"><span className="text-slate-500">Revenue</span><span className="font-bold text-slate-950">{formatReportMoney(agent.revenue)}</span></div></div>)}
          </CardContent>
        </Card>
      )}

      {(activeReport === 'developer' || scope === 'developer') && (
        <Card>
          <CardHeader><CardTitle>Developer project analytics</CardTitle><CardDescription>Unit sales must be read together with construction progress. Selling ahead of proof creates later conflict.</CardDescription></CardHeader>
          <CardContent className="h-[340px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={developerPerformance}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="project" tick={{ fontSize: 11 }} />
                <YAxis />
                <Tooltip formatter={(value, name) => name === 'revenue' ? formatReportMoney(Number(value)) : value} />
                <Bar dataKey="sold" fill="#059669" radius={[8, 8, 0, 0]} />
                <Bar dataKey="progress" fill="#b98d24" radius={[8, 8, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      )}

      <SimpleDataTable data={scopedInsights} columns={insightColumns} searchPlaceholder="Search insights..." />

      {activeReport === 'exports' && <SimpleDataTable data={exportHistory} columns={exportColumns} searchPlaceholder="Search export history..." />}

      <Card className="border-emerald-200 bg-emerald-50">
        <CardContent className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <div>
            <p className="font-bold text-emerald-950">Reports module added as a decision layer.</p>
            <p className="mt-1 text-sm text-emerald-900">The next serious upgrade is real Supabase aggregation queries. Static charts are useful for layout; production reports need live metrics.</p>
          </div>
          <Button variant="default" size="sm"><FileSpreadsheet className="h-4 w-4" /> Generate report</Button>
        </CardContent>
      </Card>
    </div>
  );
}
