import {
  BarChart3,
  Bell,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  Calculator,
  ClipboardList,
  Coins,
  FileText,
  FolderKanban,
  GitBranch,
  Handshake,
  Home,
  LayoutDashboard,
  LifeBuoy,
  LineChart,
  Megaphone,
  MessageSquareText,
  ReceiptText,
  SearchCheck,
  Settings,
  ShieldCheck,
  Star,
  UserCog,
  UsersRound,
  WalletCards,
  Wrench,
  Store,
} from 'lucide-react';
import type { NavItem } from '@/types/navigation';
import type { RouteRole, UserRole } from '@/types/roles';

export const routeToUserRole: Record<RouteRole, UserRole> = {
  'super-admin': 'super_admin',
  agency: 'agency_admin',
  agent: 'agent',
  client: 'client',
  landlord: 'landlord',
  'service-provider': 'service_provider',
  developer: 'developer',
  finance: 'finance_staff',
};

export const userRoleToRoute: Record<UserRole, RouteRole> = {
  super_admin: 'super-admin',
  agency_admin: 'agency',
  agent: 'agent',
  client: 'client',
  landlord: 'landlord',
  service_provider: 'service-provider',
  developer: 'developer',
  finance_staff: 'finance',
};

export const roleLabels: Record<UserRole, string> = {
  super_admin: 'Super Admin',
  agency_admin: 'Agency Admin',
  agent: 'Agent',
  client: 'Client/User',
  landlord: 'Landlord/Seller',
  service_provider: 'Service Provider',
  developer: 'Developer',
  finance_staff: 'Finance/Staff',
};

export const roleDescriptions: Record<UserRole, string> = {
  super_admin: 'Controls the entire platform, agencies, users, access and system activity.',
  agency_admin: 'Manages agency operations, branches, agents, clients, leads and reports.',
  agent: 'Works assigned leads, clients, properties, appointments and commissions.',
  client: 'Browses properties, saves listings, sends inquiries and books appointments.',
  landlord: 'Submits properties, tracks inquiries, viewings, documents and valuation requests.',
  service_provider: 'Receives service requests, submits quotes and manages portfolio.',
  developer: 'Manages projects, units, construction progress and project sales.',
  finance_staff: 'Handles invoices, receipts, expenses, payroll and financial reporting.',
};

export const validRouteRoles: RouteRole[] = [
  'super-admin',
  'agency',
  'agent',
  'client',
  'landlord',
  'service-provider',
  'developer',
  'finance',
];

export function isRouteRole(value: string): value is RouteRole {
  return validRouteRoles.includes(value as RouteRole);
}

export const navigationByRole: Record<RouteRole, NavItem[]> = {
  'super-admin': [
    { title: 'Overview', href: '/dashboard/super-admin', icon: LayoutDashboard },
    { title: 'Agencies', href: '/dashboard/super-admin/agencies', icon: Building2 },
    { title: 'Users', href: '/dashboard/super-admin/users', icon: UsersRound },
    { title: 'Roles & Access', href: '/dashboard/super-admin/roles-access', icon: ShieldCheck },
    { title: 'Reports & Activity', href: '/dashboard/super-admin/activity', icon: BarChart3 },
    { title: 'Marketing', href: '/dashboard/super-admin/marketing', icon: Megaphone },
    { title: 'Support', href: '/dashboard/super-admin/support', icon: LifeBuoy },
    { title: 'Subscriptions', href: '/dashboard/super-admin/subscriptions', icon: WalletCards },
    { title: 'Risk Control', href: '/dashboard/super-admin/risk-control', icon: ShieldCheck },
    { title: 'Settings', href: '/dashboard/super-admin/settings', icon: Settings },
  ],
  agency: [
    { title: 'Overview', href: '/dashboard/agency', icon: LayoutDashboard },
    { title: 'Branches', href: '/dashboard/agency/branches', icon: Building2 },
    { title: 'Agents', href: '/dashboard/agency/agents', icon: UserCog },
    { title: 'Clients', href: '/dashboard/agency/clients', icon: UsersRound },
    { title: 'Properties', href: '/dashboard/agency/properties', icon: Home },
    { title: 'Leads', href: '/dashboard/agency/leads', icon: ClipboardList },
    { title: 'Appointments', href: '/dashboard/agency/appointments', icon: CalendarDays },
    { title: 'Follow-ups', href: '/dashboard/agency/follow-ups', icon: Bell },
    { title: 'Transactions', href: '/dashboard/agency/transactions', icon: Handshake },
    { title: 'Marketing', href: '/dashboard/agency/marketing', icon: Megaphone },
    { title: 'Valuation', href: '/dashboard/agency/valuation', icon: Calculator },
    { title: 'AI Assistant', href: '/dashboard/agency/ai-assistant', icon: BrainCircuit },
    { title: 'Discovery', href: '/dashboard/agency/discovery', icon: SearchCheck },
    { title: 'Referrals', href: '/dashboard/agency/referrals', icon: GitBranch },
    { title: 'Property Mgmt', href: '/dashboard/agency/property-management', icon: Wrench },
    { title: 'Services', href: '/dashboard/agency/services', icon: Store },
    { title: 'Finance', href: '/dashboard/agency/finance', icon: Coins },
    { title: 'Invoices', href: '/dashboard/agency/invoices', icon: ReceiptText },
    { title: 'Receipts', href: '/dashboard/agency/receipts', icon: WalletCards },
    { title: 'Documents', href: '/dashboard/agency/documents', icon: FileText },
    { title: 'Verification', href: '/dashboard/agency/verification', icon: ShieldCheck },
    { title: 'Subscription', href: '/dashboard/agency/subscription', icon: WalletCards },
    { title: 'Risk Control', href: '/dashboard/agency/risk-control', icon: ShieldCheck },
    { title: 'Reports', href: '/dashboard/agency/reports', icon: LineChart },
    { title: 'Support', href: '/dashboard/agency/support', icon: LifeBuoy },
    { title: 'Settings', href: '/dashboard/agency/settings', icon: Settings },
  ],
  agent: [
    { title: 'Overview', href: '/dashboard/agent', icon: LayoutDashboard },
    { title: 'My Leads', href: '/dashboard/agent/leads', icon: ClipboardList },
    { title: 'My Clients', href: '/dashboard/agent/clients', icon: UsersRound },
    { title: 'My Properties', href: '/dashboard/agent/properties', icon: Home },
    { title: 'Appointments', href: '/dashboard/agent/appointments', icon: CalendarDays },
    { title: 'Follow-ups', href: '/dashboard/agent/follow-ups', icon: Bell },
    { title: 'Transactions', href: '/dashboard/agent/transactions', icon: Handshake },
    { title: 'Marketing', href: '/dashboard/agent/marketing', icon: Megaphone },
    { title: 'Valuation', href: '/dashboard/agent/valuation', icon: Calculator },
    { title: 'AI Assistant', href: '/dashboard/agent/ai-assistant', icon: BrainCircuit },
    { title: 'Discovery', href: '/dashboard/agent/discovery', icon: SearchCheck },
    { title: 'Referrals', href: '/dashboard/agent/referrals', icon: GitBranch },
    { title: 'Property Mgmt', href: '/dashboard/agent/property-management', icon: Wrench },
    { title: 'Documents', href: '/dashboard/agent/documents', icon: FileText },
    { title: 'Verification', href: '/dashboard/agent/verification', icon: ShieldCheck },
    { title: 'Commissions', href: '/dashboard/agent/commissions', icon: Coins },
    { title: 'Support', href: '/dashboard/agent/support', icon: LifeBuoy },
  ],
  client: [
    { title: 'Overview', href: '/dashboard/client', icon: LayoutDashboard },
    { title: 'Browse Properties', href: '/dashboard/client/browse-properties', icon: Home },
    { title: 'Saved Properties', href: '/dashboard/client/saved-properties', icon: Star },
    { title: 'My Inquiries', href: '/dashboard/client/inquiries', icon: MessageSquareText },
    { title: 'Appointments', href: '/dashboard/client/appointments', icon: CalendarDays },
    { title: 'Transactions', href: '/dashboard/client/transactions', icon: Handshake },
    { title: 'Services', href: '/dashboard/client/services', icon: Store },
    { title: 'Documents', href: '/dashboard/client/documents', icon: FileText },
    { title: 'Verification', href: '/dashboard/client/verification', icon: ShieldCheck },
    { title: 'Support', href: '/dashboard/client/support', icon: LifeBuoy },
    { title: 'Profile', href: '/dashboard/client/settings', icon: Settings },
  ],
  landlord: [
    { title: 'Overview', href: '/dashboard/landlord', icon: LayoutDashboard },
    { title: 'Submit Property', href: '/dashboard/landlord/submit-property', icon: Home },
    { title: 'My Properties', href: '/dashboard/landlord/properties', icon: Building2 },
    { title: 'Inquiries', href: '/dashboard/landlord/inquiries', icon: MessageSquareText },
    { title: 'Appointments', href: '/dashboard/landlord/appointments', icon: CalendarDays },
    { title: 'Transactions', href: '/dashboard/landlord/transactions', icon: Handshake },
    { title: 'Property Mgmt', href: '/dashboard/landlord/property-management', icon: Wrench },
    { title: 'Services', href: '/dashboard/landlord/services', icon: Store },
    { title: 'Valuation', href: '/dashboard/landlord/valuation', icon: Calculator },
    { title: 'Documents', href: '/dashboard/landlord/documents', icon: FileText },
    { title: 'Verification', href: '/dashboard/landlord/verification', icon: ShieldCheck },
    { title: 'Support', href: '/dashboard/landlord/support', icon: LifeBuoy },
    { title: 'Profile', href: '/dashboard/landlord/settings', icon: Settings },
  ],
  'service-provider': [
    { title: 'Overview', href: '/dashboard/service-provider', icon: LayoutDashboard },
    { title: 'My Profile', href: '/dashboard/service-provider/profile', icon: UserCog },
    { title: 'Service Requests', href: '/dashboard/service-provider/requests', icon: BriefcaseBusiness },
    { title: 'Quotes', href: '/dashboard/service-provider/quotes', icon: ReceiptText },
    { title: 'Portfolio', href: '/dashboard/service-provider/portfolio', icon: FolderKanban },
    { title: 'Reviews', href: '/dashboard/service-provider/reviews', icon: Star },
    { title: 'Documents', href: '/dashboard/service-provider/documents', icon: FileText },
    { title: 'Verification', href: '/dashboard/service-provider/verification', icon: ShieldCheck },
    { title: 'Support', href: '/dashboard/service-provider/support', icon: LifeBuoy },
  ],
  developer: [
    { title: 'Overview', href: '/dashboard/developer', icon: LayoutDashboard },
    { title: 'Projects', href: '/dashboard/developer/projects', icon: FolderKanban },
    { title: 'Units', href: '/dashboard/developer/units', icon: Building2 },
    { title: 'Sales', href: '/dashboard/developer/sales', icon: ReceiptText },
    { title: 'Marketing', href: '/dashboard/developer/marketing', icon: Megaphone },
    { title: 'Progress', href: '/dashboard/developer/progress', icon: LineChart },
    { title: 'Documents', href: '/dashboard/developer/documents', icon: FileText },
    { title: 'Verification', href: '/dashboard/developer/verification', icon: ShieldCheck },
    { title: 'Reports', href: '/dashboard/developer/reports', icon: BarChart3 },
    { title: 'Support', href: '/dashboard/developer/support', icon: LifeBuoy },
  ],
  finance: [
    { title: 'Overview', href: '/dashboard/finance', icon: LayoutDashboard },
    { title: 'Invoices', href: '/dashboard/finance/invoices', icon: ReceiptText },
    { title: 'Receipts', href: '/dashboard/finance/receipts', icon: WalletCards },
    { title: 'Transactions', href: '/dashboard/finance/transactions', icon: Handshake },
    { title: 'Expenses', href: '/dashboard/finance/expenses', icon: Coins },
    { title: 'Payroll', href: '/dashboard/finance/payroll', icon: UsersRound },
    { title: 'Reports', href: '/dashboard/finance/reports', icon: BarChart3 },
    { title: 'Subscriptions', href: '/dashboard/finance/subscriptions', icon: WalletCards },
    { title: 'Risk Control', href: '/dashboard/finance/risk-control', icon: ShieldCheck },
    { title: 'Support', href: '/dashboard/finance/support', icon: LifeBuoy },
  ],
};
